apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: detection-experiments-pvc
  namespace: detection1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Ti
  volumeName: detection-experiments-pv  # Static bind
  storageClassName: ""                  # Empty for manual
